version: "3.9"
services:
  app:
    build:
      context: .
    environment:
      STAGE: prod
      HOST_PORT: 3000
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: toor
      DB_NAME: xignature
      JWT_SECRET: d&?c]B76Xzw2+')3-*JF6QBbf#`NX'<y3'$f.xr,r<HJ_9!>gx@]/RjUx]EP4_Y4
    depends_on:
      - postgres
    ports:
      - '80:3000'
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: toor
      POSTGRES_DB: xignature
    ports:
      - '5432:5432'
    volumes:
      - app-db:/var/lib/postgresql/data

volumes:
  app-db:
